spring:
  mail:
    #邮件的发送服务器地址
    host: smtp.qq.com
    #邮件发送人的账号
    username: 2312697938@qq.com
    #邮件服务的第三方授权码，不是请求密码
    password: iwhqlxsebcwqdjhb
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          debug: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true